# -------------------------------------------------------------------------- #
# Assume valores default do processamento

FAKE=0
N_DEB=0
DEBUG="0"

# Controle de envio
NOXMT="0"
OPC_XMT=""

# Controle de modo de processamento
NOINCR="0"
OPC_FULL=""

# Controle de coleta de dados
NODATA="0"
OPC_DATA=""

# Controle de erros
NOERRO="0"
OPC_ERRO=""

# Controle de COMMIT
NOCOMM="0"
OPC_COMM=""

# Por default os dados veem do diretorio de trabalho
PATH_DATA="xml.index"

# Quantidade maxima de chamadas simultaneas de indexacao de MDL
MAXPARALELO=6
